on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday

name: update

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: r-lib/actions/setup-r@v2

      - name: Install
        run: Rscript -e 'install.packages(c("yaml", "scholar"))'

      - name: Run update script
        run: Rscript _R/update-citations.R

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: main
          folder: .
